/**
 * Entity class representing a Role.
 * This class maps to a database table and defines the structure of the Role entity.
 */
package org.helha.be.sortieappbackend.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

/**
 * Represents a Role entity with associated attributes and relationships.
 */
@Data
@Entity
public class Role {

    /**
     * Unique identifier for the Role.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id_role;

    /**
     * The name of the Role.
     */
    private String name_role;

    /**
     * One-to-Many relationship with the User entity.
     * Indicates that a Role can be associated with multiple Users.
     * Ignores the role of each User during JSON serialization/deserialization.
     */
    @OneToMany(mappedBy = "role_user", cascade = CascadeType.ALL)
    @JsonIgnoreProperties("role") // Ignore the role of each User during serialization
    private List<User> users;

    /**
     * Default constructor.
     */
    public Role() {}

    /**
     * Constructor to initialize a Role object with specific values.
     *
     * @param id_role  the unique identifier of the Role.
     * @param name_role the name of the Role.
     * @param users    the list of Users associated with the Role.
     */
    public Role(int id_role, String name_role, List<User> users) {
        this.id_role = id_role;
        this.name_role = name_role;
        this.users = users;
    }
}
