name: sortie_app_frontend
description: "Frontend of SortieApp Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_profile.jpg