services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
    volumes:
      - ./data/mariadb/mysql:/var/lib/mysql:rw
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080